#!/usr/bin/env python


from uchuutools import convert_halocat_to_h5
import argparse
descr = "Convert ascii halo catalogs from Rockstar or "\
        "Consistent-Trees into hdf5 (optionally in MPI parallel)"
parser = argparse.ArgumentParser(description=descr)
parser.add_argument('outputdir', metavar='<output directory>', type=str,
                    help='the output directory for the hdf5 file(s)')
parser.add_argument("filenames", metavar="<halo catalogues>",
                    type=str, nargs='+',
                    help="list of input (ascii) halo catalogues")

prog_group = parser.add_mutually_exclusive_group()
prog_group.add_argument("-p", "--progressbar", dest='show_progressbar',
                        action="store_true", default=True,
                        help="display a progressbar on rank=0")
prog_group.add_argument("-np", "--no-progressbar", dest='show_progressbar',
                        action='store_false', help="disable the progressbar")

# Do you want to write each halo as a struct (i.e., ALL the
# properties of any given halo are written together, array of structures),
# or do you want to write out individual datasets for each of the
# halo properties (i.e., any given property of ALL halos are written
# together, structure of arrays -> default)
# write_halo_props_cont = True     # True -> structure of arrays,
#                                  # False-> array of structures
group = parser.add_mutually_exclusive_group()
group.add_argument("-m", "--multiple-dsets", dest='write_halo_props_cont',
                   action="store_true", default=True,
                   help="write a separate dataset for each halo property")
group.add_argument("-s", "--single-dset", dest='write_halo_props_cont',
                   action="store_false", default=False,
                   help="write a single dataset containing all halo "
                        "properties")
args = parser.parse_args()
try:
    from mpi4py import MPI
    comm = MPI.COMM_WORLD
except ImportError:
    comm = None

convert_halocat_to_h5(args.filenames, outputdir=args.outputdir,
                      write_halo_props_cont=args.write_halo_props_cont,
                      comm=comm, show_progressbar=args.show_progressbar)


